#!/bin/bash
#
#SBATCH -t 0-0:05 # time (D-HH:MM)
#SBATCH -p OMP    # partycja OMP
#SBATCH -c 3      # liczba rdzeni
#SBATCH -o slurm.%N.%j.out # STDOUT
#SBATCH -e slurm.%N.%j.err # STDERR

if [ -n "$SLURM_CPUS_PER_TASK" ]; then
  omp_threads=${SLURM_CPUS_PER_TASK}
else
  omp_threads=1
fi

export OMP_NUM_THREADS=${omp_threads}

executable=$(<x.txt)

/usr/bin/time ./$executable 248 2>&1

